const { __ } = wp.i18n;
const { select } = wp.data;
const { createHigherOrderComponent } = wp.compose;
const { InspectorAdvancedControls } = wp.blockEditor;
const { TextareaControl } = wp.components;

const withInspectorControls = createHigherOrderComponent((BlockEdit) => {
    return (props) => {

        const { inlineStyle } = props.attributes;
        const isAdmin = select('core').canUser('create', 'users');

        return (
            <>
                <BlockEdit {...props} />
                {isAdmin ?
                    <InspectorAdvancedControls key="inspector">
                        <TextareaControl
                            label={__('Inline styling', 'custom-blocks')}
                            help={__('Notice: This inline style will override any other inline style generated by Gutenberg.', 'custom-blocks')}
                            value={inlineStyle}
                            onChange={inlineStyle => props.setAttributes({ inlineStyle })}
                        />
                    </InspectorAdvancedControls>
                    : ''}
            </>
        );
    };
}, 'withInspectorControl');

wp.hooks.addFilter('editor.BlockEdit', 'myguten-block/src/inspector', withInspectorControls);